spring:
  application:
    name: ControleMercado-worker
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 2.0

app:
  myport: ${PORT:0}
server:
  port: ${app.myport}