server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: mercado-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:mercado
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  rabbitmq:
    host: RABBITMQ
    port: 5672
    username: mercado
    senha: 321456789
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVICE:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      avalicaoService:
        register-health-indicator: true
        minimum-number-of-calls: 1
        sliding-window-size: 3
        wait-duration-in-open-state:
          seconds: 500