server:
  port: 8888
spring:
  profiles:
    active: docker+
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lewilsonEstudos/config-pos
          clone-on-start: true
          search-paths:
            - "config"
          username: lewilsonestudos
          password: 