spring:
  profiles:
    active: docker
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: produto-service
server:
  port: 8080
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123654
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka